version: '3.8'
services:
  # Development Server
  thought-bank-backend:
    image: thought-bank-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:3000'
    volumes:
      - .:/app
