# Docker

### Get list of thoughts
GET http://localhost:8080/api/thoughts

### Create a thought
POST http://localhost:8080/api/thoughts/create
Content-Type: application/json

{
  "make": "Porsche",
  "model": "Taycan",
  "year": 2021,
  "price": 34000,
  "mileage": 10,
  "lng": 34.0522,
  "lat": -118.2437
}

# Local 

### Get list of thoughts
GET http://localhost:3000/api/thoughts

### Create a thought
POST http://localhost:3000/api/thoughts/create
Content-Type: application/json

{
  "title": "Test2",
  "content": "Thoughts3"
}

### Delete thought
DELETE http://localhost:3000/api/thoughts/delete?id=65a837ee-de0e-44f2-b55e-84478ff3e6d5